export const CAPTURE_TEXT = {
  addMovie: "영화를 추가하세요",
  apply: "적용",
  defaultVariant: "기본",
  downloadEach: "개별 다운로드",
  emptySlot: "빈 슬롯",
  externalImageHelp: "외부 이미지 URL을 붙여 넣으면 현재 선택한 커버 이미지로 사용할 수 있습니다.",
  externalImageInvalid: "http:// 또는 https://로 시작하는 이미지 URL을 입력하세요.",
  externalImageRequired: "이미지 URL을 입력하세요.",
  footerLeft: "",
  footerRight: "35Film",
  movieCopyEmpty: "영화를 추가하면 복사용 텍스트가 표시됩니다.",
  movieListCenterTitleFallback: "영화를 추가하세요",
  movieListPairSeparator: " · ",
  moviePreviewEmpty: "영화를 추가하면 선택한 이미지가 표시됩니다.",
  newsBodyText: "데이비드 존슨 주연의\n새로운 블랙 팬서\n2028.12.15 개봉",
  newsFallbackHeadline: "영화 소식",
  newsHeadline: "소식",
  notePlaceholder: "오른쪽 문구",
  overviewMissing: "한국어 overview가 없습니다.",
  releaseBoardTitle: "총정리",
  rowLabelSuffix: "번",
  slotHelpEmpty: "상단 검색으로 영화를 추가하세요.",
  slotHelpSelected: "목록과 커버에서 선택한 이미지가 사용됩니다.",
  slotsAutoFill: "영화를 추가하면 빈 슬롯이 자동으로 채워집니다.",
  singlePreviewBody: "여기에 설명을 적어주세요.\n두 줄까지 표시됩니다.",
  spotlightVariant: "스포트라이트",
  subtitlePlaceholder: "서브타이틀",
  textModeCenter: "중앙 표시",
  textModeCorner: "하단 표시",
  titlePlaceholder: "제목",
  twoColumnJoinLabel: "2열",
  oneColumnJoinLabel: "1열",
  rankingHeadline: "오늘의 영화 순위",
} as const;
